extends Node2D

class_name Passenger

const NAMES = [
	"Miguel Lowery",
	"Mckenzie Valentine",
	"Augustus Haney",
	"Camille Wise",
	"Jaron Jacobson",
	"Makena Copeland",
	"Braylon Ho",
	"Janiya Massey",
	"Heather Berg",
	"Aden Wilkerson",
	"Nathalia Humphrey",
	"Melody Richards",
	"Danika Mcgee",
	"Sonia Boone",
	"Rodrigo Mccormick",
	"Easton Mcmahon",
	"Deanna Todd",
	"Sean Miles",
	"Gabriella Reed",
	"Leroy Smith",
	"Drake Schroeder",
	"Tucker Salas",
	"Isabella Klein",
	"Dulce Gregory",
	"Layton Chaney",
	"Claudia Dyer",
	"Deandre Marquez",
	"Ayana Kent",
	"Braden Vazquez",
	"Harper Rodriguez",
	"Yosef Wolfe",
	"Spencer Gordon",
	"Ashley Rasmussen",
	"Lacey Mitchell",
	"Joanna Oliver",
	"Aaron Graves",
	"Nehemiah Gates",
	"Rubi Caldwell",
	"Moshe Murray",
	"Neil Burke",
	"Tony Tran",
	"Ryan Hanson",
	"Ryker Mosley",
	"Remington Mayo",
	"Kian Mayer",
	"Devin Pratt",
	"Isla Baldwin",
	"Maggie Michael",
	"Grayson Contreras",
	"America Brady",
	"Cassie Trevino",
	"Makenna Anderson",
	"Lilia Hodge",
	"Yareli Castillo",
	"Esmeralda Dickerson",
	"Edwin Carson",
	"Kason Wiley",
	"Amari Carpenter",
	"Brogan Holden",
	"Ace Wood",
	"Brenda Herman",
	"Dania Clayton",
	"Johanna Brennan",
	"Jermaine Malone",
	"Jadyn Bruce",
	"Maya Hodge",
	"Aisha Drake",
	"America Browning",
	"Sincere Boyle",
	"Pedro Richard",
	"Raegan Gentry",
	"Yaretzi Dillon",
	"Precious Berg",
	"Talia Caldwell",
	"Alexis Grant",
	"Bianca Wu",
	"Adriana Gomez",
	"Kaitlin Chapman",
	"Luz Wiggins",
	"Mira Serrano",
	"Belen Bell",
	"Niko Sullivan",
	"Amari Pope",
	"Oswaldo Simmons",
	"Mark Sampson",
	"Tyshawn Wiggins",
	"Adeline Maldonado",
	"Kate Bryant",
	"Chase Harvey",
	"Marlon Lloyd",
	"Barbara Guerra",
	"Adrianna Stevenson",
	"Tatiana Donaldson",
	"Cassidy Hayes",
	"Eugene Wiley",
	"Jarrett Kent",
	"Lilah Massey",
	"Johan Gould",
	"Livia Galvan",
	"Patrick Compton",
	"Santino Galvan",
	"Brenda Sexton",
	"Derrick Bishop",
	"Johnathon Gates",
	"Madilynn Turner",
	"Benjamin Boone",
	"Kasen Peck",
	"Elisha David",
	"Haven Bonilla",
	"Cael Hunt",
	"Tamia Stone",
	"Layla Sloan",
	"Ana Henderson",
	"Pierce Larson",
	"Yasmine Clarke",
	"Brynlee Beasley",
	"Milton Blackwell",
	"Dayami Shepherd",
	"Adam Griffin",
	"Kian Oconnell"
]

export(Array, Color) var HairColors

onready var PassengerSprite: Sprite = get_node("sprite")

var PassengerName: String

# Lifecycle Methods
func _ready() -> void:
	pass
	
# General Methods
func RandomizePassenger() -> void:
	randomize()
	PassengerName = NAMES[rand_range(0, NAMES.size())]
